config/routes.rb
Rails.application.routes.draw do

  #管理者ログイン　URL /admin/sign=in...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  get 'admin' => 'admin/homes#top'

  #管理者
  namespace :admin do
    resources :posts, only: [:show, :edit, :update, :destroy, :index]
    resources :users, only: [:show, :edit, :update]

  end

  #ユーザーログイン URL /users/sign_in....
  devise_for :user,controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'

  }

  #ゲストユーザーログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

  #ユーザー
  scope module: :user do
    resources :posts, only: [:index, :show, :new, :create, :edit]
  end

  root to: 'user/homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 def self.guest
   find_or_create_by!(email: "guest@aiu.com") do |user|
     user.password = SecureRandom.urlsafe_base64
     user.nick_name = "ゲスト"
     user.prefectural = "ゲスト大分県"
     user.city = "ゲストシティ"
   end
 end

  has_many :posts, dependent: :destroy

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    #@post = Post.find(params[:id])
    @users = @user.posts
  end

  def edit
    @user = User.find(params[:id])
    @users = @user.posts
  end

  def update
    @user = User.find(params[:id])
    #@users = @user.posts
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end


  private

  def user_params
    params.require(:user).permit(:nick_name, :email, :prefectural, :city)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to posts_path
  end



  def post_params
    params.require(:post).permit(:title, :introduction, :image, :tourist_spot)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
   before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name, :email, :encrypted_password, :city, :prefectural])
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
 before_action :configure_permitted_parameters

  def after_sign_in_path_for(resource)
    root_path
  end

 def guest_sign_in
  user = User.guest
  sign_in user
  flash[:notice]='ゲストユーザーとしてログインしました'
  redirect_to root_path
 end

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password])
 end


end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="badge bg-light">
      <h4><%= @user.nick_name %>さんの会員情報編集</h4>
    </div>
  </div>
  <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
  <div class="row mt-2">
    <%= f.label :会員ID, class: " h5 col-3" %>
    <%= @user.id %>
  </div>
  <div class="row mt-2">
    <%= f.label :ペンネーム, class: " h5 col-3" %>
    <%= f.text_field :nick_name %>
  </div>
  <div class="row mt-2">
    <%= f.label :メールアドレス, class: "h5 col-3" %>
    <%= f.text_field :email %>
  </div>
  <div class="row mt-2">
    <%= f.label :県, class: "h5 col-3" %>
    <%= f.text_field :prefectural %>
  </div>
  <div class="row mt-2">
    <%= f.label :市, class: "h5 col-3" %>
    <%= f.text_field :city %>
  </div>
  <%= f.submit '変更を保存', class: "col-2 mt-3 offset-3 btn btn-success" %>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row mt-3 offset-1">
    <div class="badge bg-light">
      <h4><%= @user.nick_name %>さんの詳細</h4>
    </div>
    <div class="col-3">
      <%= link_to "編集する", edit_admin_user_path(@user.id), class: "offset-3 btn btn-success" %>
    </div>
  </div>
  <div class="row mt-4 offset-2">
    <div class="col-2 badge bg-light">
      <h5>会員ID</h5>
    </div>
    <div class="col-4 ml-4">
      <h5><%= @user.id %></h5>
    </div>
  </div>
  <div class="row mt-2 offset-2">
    <div class="col-2 badge bg-light">
      <h5>登録名</h5>
    </div>
    <div class="col-4 ml-4">
      <h5><%= @user.nick_name %></h5>
    </div>
  </div>
  <div class="row mt-2 offset-2">
    <div class="col-2 badge bg-light">
      <h5>メールアドレス</h5>
    </div>
    <div class="col-4 ml-4">
      <h5><%= @user.email %></h5>
    </div>
  </div>
  <div class="row mt-2 offset-2">
    <div class="col-2 badge bg-light">
      <h5>登録住所</h5>
    </div>
    <div class="col-4 ml-4">
      <h5><%= @user.prefectural %><%= @user.city %></h5>
    </div>
  </div>
  <div class="row mt-2 offset-2">
    <div class="col-2 badge bg-light">
      <h5>登録日</h5>
    </div>
    <div class="col-4 ml-4">
      <h5><%= @user.created_at.strftime('%Y/%m/%d/ %H:%M') %></h5>
    </div>
  </div>
  <div class="row mt-2 offset-2">
    <table class="table table-success table-striped">
      <thead>
        <tr>
          <th>投稿日</th>
          <th>タイトル</th>
          <th>内容</th>
          <th>写真</th>
          <th>タグ</th>
          <th>削除</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.created_at.strftime('%Y/%m/%d %H:%M') %></td>
          <td><%= user.title %></td>
          <td><%= user.introduction %></td>
          <td><%= image_tag user.image, size: "100x100" %></td>
          <td></td>
          <td><%= link_to "削除する", admin_post_path(user.id), method: :delete, class: "col-8 ml-2 btn btn-danger" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>