config/routes.rb
Rails.application.routes.draw do

  #管理者ログイン　URL /admin/sign=in...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  get 'admin' => 'admin/homes#top'

  #管理者
  namespace :admin do
    resources :posts, only: [:show, :edit, :update, :destroy, :index]
    resources :users, only: [:show, :edit, :update]

  end

  #ユーザーログイン URL /users/sign_in....
  devise_for :user,controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'

  }

  #ゲストユーザーログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

  #ユーザー
  scope module: :user do
    resources :posts, only: [:index, :show, :new, :create, :edit]
  end

  root to: 'user/homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 def self.guest
   find_or_create_by!(email: "guest@aiu.com") do |user|
     user.password = SecureRandom.urlsafe_base64
     user.nick_name = "ゲスト"
     user.prefectural = "ゲスト大分県"
     user.city = "ゲストシティ"
   end
 end

  has_many :posts, dependent: :destroy

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @users = User.all
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin__path
  end


end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    #@post = Post.find(params[:id])
    @users = @user.posts
  end

  def edit
    @user = User.find(params[:id])
    @users = @user.posts
  end

  def update
    @user = User.find(params[:id])
    #@users = @user.posts
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end


  private

  def user_params
    params.require(:user).permit(:nick_name, :email, :prefectural, :city)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to posts_path
  end



  def post_params
    params.require(:post).permit(:title, :introduction, :image, :tourist_spot)
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guest_sessions_helper.rb
module GuestSessionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container text-center">
        <div class="row mt-4">
          <% if  user_signed_in? && current_user.email == "guest@aiu.com" %>
            <button type="button" class="btn btn-outline-secondary mx-2">
              <%= link_to "新規登録", new_user_registration_path %>
            </button>
            <button type="button" class="btn btn-outline-secondary mx-2">
              投稿一覧
            </button>
            <button type="button" class="btn btn-outline-primary mx-2">
             <%= link_to "top", root_path %>
            </button>
            <button type="button" class="btn btn-outline-primary mx-2">
             <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </button>
            <%= flash[:notice] %>
            <div class="col-4">
              <p>ゲストログイン中</p>
            </div>
           <% elsif user_signed_in? %>
             <button type="button" class="btn btn-outline-primary mx-2">
              <%= link_to "top", root_path %>
             </button>
             <button type="button" class="btn btn-outline-primary mx-2">
               マイページ
             </button>
             <button type="button" class="btn btn-outline-primary mx-2">
               about
             </button>
             <button type="button" class="btn btn-outline-primary mx-2">
               <%= link_to "新規投稿", new_post_path %>
             </button>
             <button type="button" class="btn btn-outline-primary mx-2">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
             </button>
          <% elsif admin_signed_in? %>
           <button type="button" class="btn btn-outline-primary mx-2">
             <%= link_to "管理者ログイン", new_admin_session_path %>
           </button>
           <button type="button" class="btn btn-outline-primary mx-2">
             <%= link_to "投稿一覧", admin_path %>
           </button>
           <button type="button" class="btn btn-outline-primary mx-2">
             <%= link_to "会員一覧", admin_path %>
           </button>
           <button type="button" class="btn btn-outline-primary mx-2">
             <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
           </button>
           <div class="col-4">
               <p>管理者としてログイン中</p>
           </div>
          <% else %>
            <button type="button" class="btn btn-outline-secondary mx-2">
               <%= link_to "ログイン", new_user_session_path %>
            </button>
            <button type="button" class="btn btn-outline-secondary mx-2">
              <%= link_to "新規登録", new_user_registration_path %>
            </button>
            <button type="button" class="btn btn-outline-secondary mx-2">
              about
            </button>
            <button type="button" class="btn btn-outline-secondary mx-2">
              投稿一覧
            </button>
            <button type="button" class="btn btn-outline-secondary mx-2">
           　<%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %>
            </button>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>